name: Release

on:
  push:
    tags:
      - '[0-9]+'
jobs:
  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: foo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Fetch ruby gems
      run: |
        gem fetch nais-log-parser --version "0.39.4" --source "https://rubygems.pkg.github.com/nais"
    - name: Build Docker image
      run: |
        docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF##*/} .
    - name: Login GPR
      run: |
        docker login -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN} docker.pkg.github.com
    - name: Push Docker image
      run: |
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF##*/}
